### ISSUE TITLE
with ttl option hidden data-series are not pruned [BUG]

### ISSUE THREAD

**Issue by AlexDel** [nagix/chartjs-plugin-streaming#53] opened 2018-11-14 03:54 UTC
Hello! `ttl` option is realy very handy. It allow us not manage pruning manualy. Thanks! 

But there is a bug which potentialy leads to memory leak: when some of series on chart are not visible (with `hidden:  true` config) it's items are not deleted after excessing ttl option period and keep accumulating in chart.

 [Here is a reproducer](https://plnkr.co/edit/Wt3Xt9IrtSK4hIIqI1fH)

I can facilitate with PR. Could you tell me where this can be fixed?

**Comment by nagix** [comment] 2018-11-14 04:48
Thank you for reporting the issue. This is indeed a bug, and the cause is `scale.getPixelForValue` returns `NaN` when the dataset is hidden. I uses `getPixelForValue` to get a pixel value for comparison in order to avoid time string parsing as the timestamps values are cached in the scale, but didn't noticed that they are not cached when the dataset is hidden.

The solution would be to copy the `parse` and `momentify` function code from scale.time.js to scale.realtime.js, call `parse` to get a timestamp value and use it for comparison instead of using a pixel value. Can you create a PR?

**Comment by nagix** [comment] 2018-12-11 08:59
This was fixed by 8946372.

**Closed by nagix** 2018-12-11 08:59 UTC
Labels: bug
