### ISSUE TITLE
annotation not updateing

### ISSUE THREAD

**Issue by rashearth** [nagix/chartjs-plugin-streaming#70] opened 2019-03-21 09:27 UTC
Hi, i am now using chart.js annotation plugin with streaming plugin.
I wanted to move the annotation for the sample you have made as below.
I just used random scaling factor to confirm the movement.

https://nagix.github.io/chartjs-plugin-streaming/samples/annotation.html

But I have found a problem that the annotation position does not change when I update the annotation value.

(i included both chart.update(); as well as windows.myChart, just to make sure if both doesnt work)

Do you know if this is a bug?
or i am just making it wrong...?

```		
setInterval(function (chart) {
	   
			chart.options.annotation.annotations[0].value = randomScalingFactor();
			console.log(chart.options.annotation.annotations[0].value);
			chart.update();
			windows.myChart.update();

}, 1000); 
```
<img width="779" alt="スクリーンショット 2019-03-21 18 26 24" src="https://user-images.githubusercontent.com/26535295/54743232-e9f25b80-4c06-11e9-8afd-cc7c8290b1a0.png">

**Comment by nagix** [comment] 2019-03-21 15:59
The problem is nothing to do with chartjs-plugin-streaming, but this should work:

```js
    // ...
    options: {
        annotation: {
            annotations: [{
                // id: 'hline', <-- comment out this line
                // ...
            }]
        }
    }
    // ...

setInterval(function () {
    window.myChart.options.annotation.annotations[0].value = randomScalingFactor();
    window.myChart.update({preservation: true});
}, 1000);
```

**Comment by rashearth** [comment] 2019-03-23 03:47
Thanks! it worked out well.
but unfortunately, i think that the streaming and the financial cdn script URL might be updated in the samples?
http://aifx2.sakura.ne.jp/ScriptFolder/chartjs-plugin-streaming-master/docs/samples/financial.html

it works in the old cdn, but not in the newest one.
also, i have some other issues related to newest financial chart and chart.2.8.0.

sometimes below error comes out , and the streaming stops or lags heavily.
(dont know if this issue should be listed here, but just in case)
```
chartjs-chart-financial.js:118 Uncaught TypeError: Cannot read property 'toFixed' of undefined
    at i.label (chartjs-chart-financial.js:118)
    at Chart.min.js:7
    at Object.each (Chart.min.js:7)
    at i.getBody (Chart.min.js:7)
    at i.update (Chart.min.js:7)
    at i.handleEvent (Chart.min.js:7)
    at ni.eventHandler (Chart.min.js:7)
    at i (Chart.min.js:7)
    at HTMLCanvasElement.Fe.(anonymous function) (https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js:7:77594)
```

**Comment by nagix** [comment] 2019-03-24 03:46
Unfortunately, I couldn't reproduce the error you mentioned. Does it occur in [this example](
https://nagix.github.io/chartjs-plugin-streaming/samples/financial.html)? What browser and OS are you using?

In the sample code, `onRefresh` always pushes an object with `o` property (open price value), so it doesn't seem to have a problem.

**Comment by nagix** [comment] 2019-03-24 04:02
In [your comment](https://github.com/chartjs/chartjs-chart-financial/issues/52#issuecomment-475920488), you mentioned that the data is retrieved from Firebase, so the data this plugin's sample code generates is not used, is it? In that case, as @benmccann mentioned, it is likely that your input sometimes doesn't have `o` property in the object.

**Comment by rashearth** [comment] 2019-03-24 05:19
OK i got whats the problem.


 i just listed a sample here.
if i list down candlestick with other scatter and line chart, it will go wrong.
http://aifx2.sakura.ne.jp/realtimecharttest.html
(heres the example website. i will just delete this website in severaldays.)

```
<!DOCTYPE HTML>
<html>
 <head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	
	

<head>
	<script src="https://cdn.jsdelivr.net/npm/moment@2.24.0/min/moment.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
	<script src="https://www.chartjs.org/chartjs-chart-financial/chartjs-chart-financial.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@1.8.0"></script>
</head>
<body>
	<div>
		<canvas id="myChart"></canvas>
	</div>
</body>


<script>

 
var annotationx; 
var annotationy;
 
var ask = Math.random();
 

setInterval(function () {
	
	annotationx= Date.now();
	annotationy = 90;
	return annotationx;
	return annotationy; 
	
	
}, 10000); 





function onRefresh(chart) {
	var t = Date.now();
	var data = chart.data.datasets[0].data;
	var last;

	t -= t % 5000;
	if (data.length === 0) {
		data.push({ t: t - 5000, o: 99, h: 101, l: 98, c: 100 });
	}
	last = data[data.length - 1];
	if (t != last.t) {
		var c = last.c;
		last = { t: t, o: c, h: c, l: c, c: c };
		data.push(last);
	}
	last.c += Math.random() - 0.5;
	last.h = Math.max(last.h, last.c);
	last.l = Math.min(last.l, last.c);


         chart.data.datasets[1].data.push(
			{
            x: annotationx,
            y: annotationy
        	});
        
				chart.data.datasets[2].data.push(
			{
            x: Date.now(),
            y: ask,
        	});




}

var config = {
	type: 'candlestick',
	data: {
		datasets: [{
			data: [],
			fractionalDigitsCount: 2
		},
               {
						type: 'scatter',
						label: '購入',
						
						backgroundColor: "red",
						radius: 0,
					    borderColor: "blue",
						fill: false,
						
						lineTension: 0,
						 datalabels: {
   							 display: true
 						},
						

						data: []
						
						},
						
						{
						type: 'line',
						//lineTension: 0,   
						radius: 0,
						datalabels: {
   							 display: false
 						},
						label: 'Ask',
						
						//backgroundColor: "",
					    borderColor: "red",
						borderWidth: 1,
						datalabels: {
   							 display: false
 						},
						fill: false,
						data: []
						},





]
	},
	options: {


		title: {
			display: true,
			text: 'Financial chart sample'
		},
		legend: {
			display: false,
		},
		scales: {
			xAxes: [{
				type: 'realtime',
				realtime: {
					duration: 120000,
					refresh: 500,
					delay: 0,
					onRefresh: onRefresh
				}
			}]
		},
		tooltips: {
			position: 'nearest',
			intersect: false
		},
		animation: {
			duration: 0
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('myChart').getContext('2d');
	window.myChart = new Chart(ctx, config);
};


</script>

```

**Comment by nagix** [comment] 2019-03-24 06:03
This is the problem in chartjs-chart-financial, which doesn't support mixed datatypes in a single chart, because this occurs even without chartjs-plugin-streaming. Please post your code above to chartjs/chartjs-chart-financial#52.

**Comment by rashearth** [comment] 2019-03-24 06:16
thank you for your support.  Please be noticed that the mixed chart streaming could be done in the previous version .
Will re-post the issue to the chart-financials.

**Comment by nagix** [comment] 2019-05-27 04:52
Closing as it was fixed

**Closed by nagix** 2019-05-27 04:52 UTC
Labels: question
